import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  Briefcase,
  Building,
  CalendarClock,
  ChartColumn,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  ClipboardCheck,
  Clock,
  Copy,
  Database,
  Download,
  ExternalLink,
  Eye,
  FileChartColumn,
  FileSpreadsheet,
  FileText,
  FileUp,
  Flag,
  FolderOpen,
  Gauge,
  GitCompare,
  GripVertical,
  Hourglass,
  IconNode,
  Inbox,
  Info,
  LayoutDashboard,
  Link,
  ListTodo,
  LoaderCircle,
  Lock,
  MessageSquareText,
  PanelLeft,
  Paperclip,
  Play,
  RotateCcw,
  Scale,
  ScanText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Shuffle,
  SquareKanban,
  Target,
  TrendingUp,
  TriangleAlert,
  Upload,
  UserCog,
  Users,
  X,
  Zap,
} from 'lucide';

/**
 * Registro único de ícones (Lucide). Importar somente o necessário mantém o bundle enxuto;
 * para um novo ícone, adicione-o aqui.
 */
export const ICONS = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  briefcase: Briefcase,
  building: Building,
  'calendar-clock': CalendarClock,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  copy: Copy,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'file-chart': FileChartColumn,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'file-up': FileUp,
  flag: Flag,
  'folder-open': FolderOpen,
  gauge: Gauge,
  'git-compare': GitCompare,
  grip: GripVertical,
  hourglass: Hourglass,
  inbox: Inbox,
  info: Info,
  'layout-dashboard': LayoutDashboard,
  link: Link,
  'list-todo': ListTodo,
  loader: LoaderCircle,
  lock: Lock,
  'message-square': MessageSquareText,
  'panel-left': PanelLeft,
  paperclip: Paperclip,
  play: Play,
  'rotate-ccw': RotateCcw,
  scale: Scale,
  'scan-text': ScanText,
  search: Search,
  send: Send,
  settings: Settings,
  'shield-check': ShieldCheck,
  shuffle: Shuffle,
  'square-kanban': SquareKanban,
  target: Target,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  upload: Upload,
  'user-cog': UserCog,
  users: Users,
  x: X,
  zap: Zap,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICONS;

export function isIconName(name: string): name is IconName {
  return name in ICONS;
}
